site_name: linuxdocs.net
docs_dir: docs
nav:
    - Accueil: index.md
    - Articles:
      - Linux:
        - getssl: article-getssl.md
        - motion-UI: article-motionui.md
        - pyload: article-pyload.md
      - Raspberry Pi:
        - Systeme:
          - Afficher la temperature CPU: article-raspberrypi-temperature.md
        - Videosurveillance:
          - motion-UI: article-motionui.md
    - Memo Linux:
      - Commandes: linuxcommands.md

navigation_depth: 4
theme: readthedocs
nav_style: light