site_name: My Docs
docs_dir: docs
nav:
    - Accueil: index.md
    - Articles:
      - Linux:
        - pyload: article-pyload.md
        - motion-UI: article-motionui.md
      - Raspberry Pi:
        - Systeme:
          - Afficher la temperature CPU: article-raspberrypi-temperature.md
        - Videosurveillance:
          - motion-UI: article-motionui.md
    - Memo Linux:
      - Commandes: linuxcommands.md

theme: readthedocs
